### ISSUE TITLE
Error while generating DTO - Sequence contains no elements

### ISSUE THREAD

**Issue by Sandiejat** [yohney/dto-generator#5]
**Steps to reproduce:** Right click on an entity class-> Generate DTO -> Select path of another project in the same solution-> Name DTO class-> Click OK.

**Exception Thrown:**
An exception has occurred. Please c/p stack trace to project website......
Sequence contains no elements
![image](https://cloud.githubusercontent.com/assets/6057876/23108655/43fe564e-f775-11e6-91fd-2c83ef1f96d4.png)

**Stack trace:**
`   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at DtoGenerator.Logic.Infrastructure.EntityParser.GetRelatedEntity(PropertyDeclarationSyntax p)
   at DtoGenerator.Logic.Infrastructure.EntityParser.<>c.<FromSyntaxTree>b__5_10(PropertyDeclarationSyntax p)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DtoGenerator.Logic.Infrastructure.EntityParser.FromSyntaxTree(SyntaxTree syntaxTree)
   at DtoGenerator.Logic.Infrastructure.EntityParser.<FromDocument>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DtoGenerator.Logic.UI.EntityViewModel.<CreateRecursive>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DtoGenerator.Logic.UI.PropertySelectorViewModel.<Create>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at DtoGenerator.Vsix.GenerateDtoCommand.<MenuItemCallback>d__13.MoveNext() in C:\git\dto-generator\src\DtoGenerator\DtoGenerator.Vsix\GenerateDtoCommand.cs:line 235`

**Comment by yohney** [comment]
Hey @Sandiejat !

First of all, thank you for helping me improve this plugin, and sorry for not getting back a bit earlier!
I hope you still remember what entity caused this, since the problem is that I did not handle some specific case of property type. Would you mind sending me the class and related classes, or at least any properties which do not have a simple type, such as string, int, etc..?

**Comment by weedkiller** [comment]
Hi,

FYI  I also had this with Nested Entities... the error was hard to understand.

**Comment by Sandiejat** [comment]
There are many in my case, I'm attaching one here. Feel free to let me know if more examples are needed.

Thanks for replying. It's a wonderful utility and minor bug fixings can keep it rocking!
[Staff.txt](https://github.com/yohney/dto-generator/files/801690/Staff.txt)

**Comment by yohney** [comment]
@Sandiejat Thank you for the example, I'll let you know if I need more. I'll include the example you sent into unit test and make sure it is handled well.

@weedkiller I'll look into nested entities as well. To be honest, I don't use them much, so didn't cover that case, but I'll look into it. Feel free to send me an example of how you are using it (you can scramble field names if you like).
